const express = require('express')
const authRoutes = require("./auth/auth")
const courseRoutes = require('./course/course')
const testimonialRoutes = require('./testimonial/testimonial')
const courseClassRoutes = require('./class/class')
const achievmentRoutes = require('./achievment/achievment')
const bulletinRoutes = require('./bulletin/bulletin')
const officeRoutes = require('./office/office')
const acceptedUniversity = require('./acceptedUniversity/accepted')
const bannerRoutes = require('./banner/banner')
const promoRoutes = require('./promo/promo')
const programRoutes = require('./program/program')
const facilityRoutes = require('./facility/facility')
const alumnaeRoutes = require('./alumnae/alumnae')
const congratulationRoutes = require('./congratulation/congratulation')

const router = express.Router();

router.use("/auth", authRoutes)
router.use("/course", courseRoutes)
router.use("/testimonial", testimonialRoutes)
router.use("/class", courseClassRoutes)
router.use("/achievment", achievmentRoutes)
router.use("/bulletin", bulletinRoutes)
router.use("/office", officeRoutes)
router.use("/acceptedUniversity", acceptedUniversity)
router.use("/banner", bannerRoutes)
router.use("/promo", promoRoutes)
router.use("/program", programRoutes)
router.use("/facility", facilityRoutes)
router.use("/alumnae", alumnaeRoutes)
router.use("/congratulation", congratulationRoutes)

module.exports = router